version: "3"
services:
  sql-db:
    container_name: test-sql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test-db

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci


