name: java docker image CI/CD when pulling request

on:
  pull_request:
    branches:
      - develop

permissions: write-all

jobs:
  test:
    name: unit test and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set Docker Container before build and test
        run: docker-compose -f docker-compose-test.yml up -d

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Report to CodeCov
          uses: codecov/codecov-action@v3
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push to DockerHub
        env:
          REPO: meca
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest ${{ secrets.DOCKERHUB_USERNAME }}/$REPO:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$REPO:latest

      #      - name: Deploy to ec2
      #        uses: appleboy/ssh-action@master
      #        with:
      #          host: ${{secrets.DEV_HOST}}
      #          username: ${{secrets.DEV_USERNAME}}
      #          password: ${{secrets.DEV_PASSWORD}}
      #          port: 22
      #          script: |
      #            docker-compose down
      #            sudo docker image prune -f
      #            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/meca:latest
      #            docker-compose up -d
      #      - name: Deploy to ec2
      #        uses: appleboy/ssh-action@master
      #        with:
      #          key: ${{ secrets.PROD_EC2_KEY }}
      #          host: ${{ secrets.PROD_EC2_HOST }}
      #          username: ${{ secrets.PROD_EC2_USERNAME }}
      #          port: 22
      #          script: |
      #            docker-compose down
      #            sudo docker image prune -f
      #            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/meca:latest
      #            docker-compose up -d

      - name: Close Docker Container after build and test
        run: docker-compose -f docker-compose-test.yml down